apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-dmnt
  namespace: mvp-demo-dev-namespace-sbsl-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:253d2ebdd2e715ad88c7949f4a70d338b8ce63e0d5573263af295abca2b82c56
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
